# You can omit 'version' in modern Compose; it's deprecated.
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - backend/.env
    environment:
      - PYTHONPATH=/app   # makes 'import app.models' work for Alembic

  web:
    build: ./frontend
    depends_on:
      - backend           # was 'api' before; use the actual service name
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules # keep node_modules inside container
    command: npm run dev -- --host

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI

volumes:
  pgdata:
